routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

Route::resource('/tickets', 'TicketsController');

app/Models/Note.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Note extends Model
{
    protected $fillable = [
    	'note',
    ];

    //Tickets
    public function ticket()
    {
    	return $this->belongsTo('App\Models\Ticket');
    }
}

app/Models/Ticket.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Ticket extends Model
{
    protected $fillable = [
        'group',
        'requestor',
        'priority',
        'subject',
        'description',
        'status'
    ];

    public function notes()
    {
        return $this->hasMany('Ticket');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('dashboard');
    }
}

app/Http/Controllers/TicketsController.php
<?php

namespace App\Http\Controllers;
use App\Models\Ticket;

use Illuminate\Http\Request;

class TicketsController extends Controller
{
    public function index()
    {
        $tickets = Ticket::all();
        
        return view('tickets.index', compact('tickets'));
    }

    public function create()
    {
        return view('tickets.create');

    }

    public function store(Request $request)
    {
        $request->validate([
            'subject' => 'required',
            // 'note' => 'required'
            'priority' => 'required'
        ]);

        $ticket = new Ticket([
            'priority' => $request->get('priority'),
            'subject' => $request->get('subject'),
            'group' => $request->get('group'),
            'requester' => $request->get('requester'),
            'description' => $request->get('description'),
            'status' => 'open',
        ]);
        $ticket->save();
        return redirect('/tickets')->with('success', 'Ticket was created');
    }

    public function show($id)
    {
        $ticket = Ticket::find($id);

        return view('tickets.show', compact('ticket'));
    }

    public function edit($id)
    {
        $ticket = Ticket::find($id);
        $priority_options = ["low" => "Low", "high" => "High"];
        $status_options = ["open" => "Open", "in_progress" => "In Progress", "closed" => "Closed"];

        return view('tickets.edit', compact( ['ticket', 'priority_options', 'status_options'] ));

    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'subject' => 'required',
            // 'note' => 'required'
        ]);

        $ticket = Ticket::find($id);
        $ticket->subject = $request->get('subject');
        $ticket->group = $request->get('group');
        $ticket->requester = $request->get('requester');
        // $request->validate([
        //     'title' => 'required',
        //     'note' => 'required'
        // ]);

        $ticket = Ticket::find($id);
        $ticket->priority = $request->get('priority');
        $ticket->description = $request->get('description');
        $ticket->status = $request->get('status');
        $ticket->save();

        return redirect('/tickets')->with('success', 'Ticket Has Been Updated');
    }

    public function destroy($id)
    {
        $ticket = Ticket::destroy($id);

        return redirect('/tickets')->with('success', 'Ticket Has Been Destroyed');
    }
}

resources/views/dashboard.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Nunito', sans-serif;
                font-weight: 200;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 13px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            @if (Route::has('login'))
                <div class="top-right links">
                    @auth
                        <a href="{{ url('/dashboard') }}">Dashboard</a>
                    @else
                        <a href="{{ route('login') }}">Login</a>

                        @if (Route::has('register'))
                            <a href="{{ route('register') }}">Register</a>
                        @endif
                    @endauth
                </div>
            @endif

            <div class="content">
                <div class="title m-b-md">
                    Simple Help Desk
                </div>

                
            </div>
        </div>
    </body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Simple Help Desk') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-link"><a href="/tickets">Tickets</a></li>

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/tickets/create.blade.php
@extends('layouts.app')

@section('content')
<form method="post" action="{{ route('tickets.store') }}" >
	@csrf
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Create Ticket</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

					<form method="post" action="{{ route('tickets.store') }}" >
						@csrf
						<div class="form-group">
					    	<label for="priority">Priority</label>
					    	<select name="priority" class="form-control">
					    		<option>Select A Priority</option>
					    		<option value="low">Low</option>
					    		<option value="high">High</option>
					    	</select>
					    </div>
					    <div class="form-group">
					    	<label for="subject">Subject</label>
					        <input type="text" name="subject" class="form-control" placeholder="Subject"/>
					    </div>
					    <div class="form-group">
					    	<label for="description">Description</label>
					        <textarea name="description" class="form-control" placeholder="Description" cols="6" rows="6"></textarea>
					    </div>
					    <div>
					    <a href="/tickets/" class="btn btn-secondary">Cancel</a>
					    <button class="btn btn-primary">Create</button>    
					</form>                
				</div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/tickets/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit Ticket</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

					<form method="post" action="/tickets/{{ $ticket->id }}" >
						@csrf
						{{ method_field('PATCH') }}
						<div class="form-group">
					    	<label for="priority">Priority</label>
 					    	<select name="priority" class="form-control">
					    	@foreach($priority_options as $key => $value)
								<option value="{{ $key }}" {{ $key == $ticket->priority ? 'selected' : ''}} value="{{ $ticket->priority }}">{{ $value }}</option>
							@endforeach	
					    	</select>
					    </div>
					    <div class="form-group">
					    	<label for="status">Status</label>
					    	<select name="status" class="form-control">
					    		@foreach($status_options as $key => $value)
					    			<option value="{{ $key }}" {{ $key == $ticket->status ? 'selected' : '' }} value="{{ $ticket->status }}"> {{ $value }}</option>
					    		@endforeach
					    	</select>
					    </div>
					    <div class="form-group">
					    	<label for="subject">Subject</label>
					        <input type="text" name="subject" class="form-control" value="{{ $ticket->subject }}" placeholder="Subject"/>
					    </div>
					    <div class="form-group">
					    	<label for="description">Description</label>
					        <textarea name="description" class="form-control" value="{{ $ticket->description }}" placeholder="Description" cols="6" rows="6">{{ $ticket->description }}</textarea>
					    </div>
					    <div>
					    <a href="/tickets/" class="btn btn-secondary">Cancel</a>
					    <button class="btn btn-primary">Update</button>    
					</form>                
				</div>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/tickets/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Tickets <a href="/tickets/create/" class="btn btn-primary float-right">Create</a></div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                   <table class="table table-stripped">
                   	<thead>
                   		<tr>
                   			<td>Priority</td>
                   			<td>Subject</td>
                   			<td>Description</td>
                   			<td>Status</td>
                   			<td></td>
                   		</tr>
                   	</thead>
                   	<tbody>
                   @foreach($tickets as $ticket)
                   <tr>
                   	<td>{{ $ticket->priority }}</td>
                   	<td>{{ $ticket->subject }}</td>
                   	<td>{{ $ticket->description }}</td>
                   	<td>{{ $ticket->status }}</td>
                   	<td class="btn-group">
                   		<a href="/tickets/{{ $ticket->id }}" class="btn btn-primary">View</a>
                   		<a href="/tickets/{{ $ticket->id }}/edit/" class="btn btn-success">Edit</a>
                   		<form method="post" action="{{ route('tickets.destroy', $ticket->id) }}">
                   			@csrf
                   			@method('DELETE')
                   		<button class="btn btn-danger" type="submit">Delete</button>
                   		</form> 
                   	</td>
                   	</tr>
                   @endforeach
                   	</tbody>

                   </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/tickets/show.blade.php
@extends('layouts.app')



@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Show Ticket</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

					<ul class="list-group">
						<li class="list-group-item"><strong>Priority:</strong> {{ $ticket->priority }}</li>
						<li class="list-group-item"><strong>Subject:</strong> {{ $ticket->subject }}</li>
						<li class="list-group-item"><strong>Description:</strong> {{ $ticket->description }}</li>
						<li class="list-group-item"><strong>Status:</strong> {{ $ticket->status }}</li>
					</ul>
					<br>
					<a href="/tickets" class="btn btn-danger"><< Back</a>       
				</div>
            </div>
        </div>
    </div>
</div>
@endsection